CODE SEGMENT
PORTA  EQU 00H
PORTB  EQU 02H
PORTC  EQU 04H
Config EQU 06H
ORG 0
MOV DX, Config
MOV AL, 89H
OUT DX, AL
MOV DX, PORTB

;PUT YOUR CODE HERE
START:  IN  AL, PORTC
        NOT AL
        OUT PORTB, AL
        MOV CX, 0FF00H
        LOOP $
        JMP  START
        
CODE    ENDS
END